name: Build with Nix
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build '.?submodules=1#dc32-badge'
    - uses: actions/upload-artifact@v4
      with:
        name: dc32_badge.uf2
        path: result/dc32_badge.uf2
    - uses: actions/upload-artifact@v4
      with:
        name: dc32_badge.bin
        path: result/dc32_badge.bin
    - uses: actions/upload-artifact@v4
      with:
        name: dc32_badge.elf
        path: result/dc32_badge.elf
